export enum EnvVar {
  HTTP_PORT = 'HTTP_PORT',
  LOG_LEVEL = 'LOG_LEVEL',
  LOG_DIRNAME = 'LOG_DIRNAME',
  LOG_FILENAME = 'LOG_FILENAME',
  LOG_DATE_FORMAT = 'LOG_DATE_FORMAT',
  LOG_DATE_PATTERN = 'LOG_DATE_PATTERN',
  HTTP_DEFAULT_TIMEOUT = 'HTTP_DEFAULT_TIMEOUT',
  GCEX_BASE_URL = 'GCEX_BASE_URL',
  GCEX_ADMIN_URL = 'GCEX_ADMIN_URL',
  GCEX_POR_ACCOUNT = 'GCEX_POR_ACCOUNT',
}
