export enum QueryOperator {
  EQUALS = 'equals',
  NOT_EQUALS = 'not',
  IN = 'in',
  NOT_IN = 'notIn',
  GT = 'gt',
  LT = 'lt',
  GTE = 'gte',
  LTE = 'lte',
  ADN = 'AND',
  OR = 'OR',
  NOT = 'NOT',
  CONTAINS = 'contains',
  SEARCH = 'search',
  STARTS_WITH = 'startsWith',
  ENDS_WITH = 'endsWith',
  IS_NULL = 'isNull',
  NOT_NULL = 'notNull',
  EVERY = 'every',
  SOME = 'some',
  NONE = 'none',
}
