name: Admin Deployment

on:
  push:
    branches:
      - main

jobs:

  admin-build:
    name: admin-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push the docker image to Amazon ECR
        env:
            ECR: ${{ steps.login-pf-aws-ecr.outputs.registry }}
            REPO: gcex-api
            BRANCH_NAME: ${{ github.ref_name }} # Branch name
        run: |
          IMAGE_TAG="$BRANCH_NAME-admin" 
          docker build -t $ECR/$REPO:$IMAGE_TAG  .
          docker push $ECR/$REPO:$IMAGE_TAG


######################
## Only main  ##
######################

  deploy_to_admin_main:
    name: deploy_to_admin_main
    needs: admin-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ secrets.AWS_REGION }}

          - name: Update kube config
            run: aws eks update-kubeconfig --name EKS-Tijarahholding 

          - name: deploy
            run: kubectl rollout restart deployment gcex-api-prod -n tijarah-prod
