export enum EnvVar {
  HTTP_PORT = 'HTTP_PORT',
  LOG_LEVEL = 'LOG_LEVEL',
  LOG_DIRNAME = 'LOG_DIRNAME',
  LOG_FILENAME = 'LOG_FILENAME',
  LOG_DATE_FORMAT = 'LOG_DATE_FORMAT',
  LOG_DATE_PATTERN = 'LOG_DATE_PATTERN',
}
